# Axel '0vercl0k' Souchet - April 19 2020
language: cpp

compiler:
  - clang++

os:
  - linux

sudo: required
dist: bionic

before_install:
  - sudo apt-get -y install ninja-build

env:
  - CONFIGURATION=Debug ARCH=x86
  - CONFIGURATION=RelWithDebInfo ARCH=x86
  - CONFIGURATION=Debug ARCH=x64
  - CONFIGURATION=RelWithDebInfo ARCH=x64

script:
  - python3 builder.py --configuration $CONFIGURATION --arch $ARCH --run-tests